/* =====================================================================
   Lineage V2 — DATA LAYER  (single source of truth)
   --------------------------------------------------------------------
   PEOPLE        — every narrated ancestor as a node with stable canonical
                   ID (A11..GEN1 / B12..GEN1 / C15..GEN1 / D9..GEN1).
   WORLDS        — dated world-event annotations along the time ruler.
   MIGRATIONS    — map ARROWs and the windows the map inset surfaces in.
   BEATS         — the 40-beat narration cue sheet (provisional t).
                   Re-lock Time column to the final ElevenLabs audio by
                   editing only the .t values here. Order and tree cues
                   never change; only the seconds do.
   --------------------------------------------------------------------
   Source files:
     Lineage_Canonical_Timeline_2026-05-25.md      (Part 1, 1B, 2)
     Lineage_Narration_Timestamps_2026-05-25.md    (the 40-beat cue sheet)
   All times in audio-seconds.
   ===================================================================== */
(function () {
  'use strict';

  /* ----- the four lineages (column order: merging pairs adjacent) ----- */
  var LINES = [
    { id: 'C', label: 'Bétourné dit Laviolette', origin: 'Picardy, France',
      color: 'var(--c-betourne)' },
    { id: 'D', label: 'Heppell · Lepel',          origin: 'Rhineland, Prussia',
      color: 'var(--c-heppell)' },
    { id: 'B', label: 'Mongeau dit Clermont',     origin: 'Auvergne, France',
      color: 'var(--c-mongeau)' },
    { id: 'A', label: 'Barbeau dit Boisdoré',     origin: 'Saintonge, France',
      color: 'var(--c-barbeau)' },

    { id: 'E', label: 'Lepage · Noël',         origin: 'Lauzon / Bellechasse, Quebec',
      color: 'var(--c-lepage, #b89967)' }
  ];

  /* =====================================================================
     PEOPLE — canonical Part 1 (full depth) + narrated Part 1B spouses
     Each: { id, line, gen, year, name, sub, parents, kind, t, ...flags }
     kind: 'person' | 'founder' | 'spouse' | 'union' | 'descendant'
     flags: anchor, candidate, dimmedUntil, tLight, napierville, finalUnion
     ===================================================================== */
  var PEOPLE = [

    /* ---- Line A, Barbeau (maternal) ---- */
    { id: 'A11', line: 'A', gen: 11, year: 1660, t: 480.05, kind: 'founder',
      name: 'Pierre Barbeau',
      sub: 'Pons, Saintonge · merchant family', parents: [] },
    { id: 'SP-A11', line: 'A', gen: 11, year: 1660, t: 480.05, kind: 'spouse',
      name: 'Madeleine Babin',
      sub: 'Pons, Saintonge', spouseOf: 'A11' },
    { id: 'A10', line: 'A', gen: 10, year: 1666, t: 760.30, kind: 'person',
      name: 'Jean Barbeau dit Boisdoré',
      sub: 'b. 1666 Pons · soldier of the King 1685',
      parents: ['A11'] },
    { id: 'A9',  line: 'A', gen: 9,  year: 1694, t: 830.89, kind: 'person',
      name: 'Gabriel Barbeau dit Boisdoré',
      sub: 'bap. 1694 Boucherville',
      parents: ['A10'] },
    { id: 'A8',  line: 'A', gen: 8,  year: 1725, t: 831.58, kind: 'person',
      name: 'Jean-Baptiste Barbeau dit Boisdoré',
      sub: 'bap. 1725 La Prairie',
      parents: ['A9'] },
    { id: 'A7',  line: 'A', gen: 7,  year: 1757, t: 993.97, kind: 'person',
      name: 'Joseph Barbeau dit Boisdoré',
      sub: 'bap. 1757 Saint-Constant',
      parents: ['A8'] },
    { id: 'A6',  line: 'A', gen: 6,  year: 1804, t: 1406.02, kind: 'person',
      name: 'François Régis Barbeau',
      sub: 'b. 1804 Saint-Constant · m. 1828',
      parents: ['A7'] },
    { id: 'A5',  line: 'A', gen: 5,  year: 1833, t: 1752.27, kind: 'person',
      name: 'Magloire Barbeau',
      sub: 'b. 1833 Saint-Philippe · m. 1865 Napierville',
      parents: ['A6'], napierville: true },
    { id: 'A4',  line: 'A', gen: 4,  year: 1870, t: 1768.56, kind: 'person',
      name: 'Joseph Wilfred Barbeau',
      sub: 'b. 1870 Napierville · Bill C-3 anchor',
      parents: ['A5'], anchor: true, napierville: true },
    { id: 'A3',  line: 'A', gen: 3,  year: 1906, t: 2101.22, kind: 'person',
      name: 'Rouville Ernest Barbeau',
      sub: 'b. 1906 North Adams, MA',
      parents: ['A4'] },
    { id: 'A2',  line: 'A', gen: 2,  year: 1943, t: 2246.12, kind: 'person',
      name: 'Lorraine Irene Barbeau',
      sub: 'b. 1943 North Adams · mother',
      parents: ['UN-AB'] },

    /* ---- Line B, Clermont / Mongeau (maternal) ---- */
    { id: 'B12', line: 'B', gen: 12, year: 1615, t: 308.16, kind: 'founder',
      name: 'Mathieu Mangot',
      sub: 'near Clermont-Ferrand, Auvergne', parents: [] },
    { id: 'SP-B12', line: 'B', gen: 12, year: 1615, t: 308.16, kind: 'spouse',
      name: 'Marguerite Blandette',
      sub: 'Clermont-Ferrand', spouseOf: 'B12' },
    { id: 'B11', line: 'B', gen: 11, year: 1643, t: 239.71, kind: 'person',
      name: 'Antoine Mangot',
      sub: 'bap. 1643 Saint-Pierre, Clermont-Ferrand',
      parents: ['B12'] },
    { id: 'SP-B11', line: 'B', gen: 11, year: 1643, t: 239.71, kind: 'spouse',
      name: 'Gabrielle Pabiot',
      sub: 'Clermont-Ferrand', spouseOf: 'B11' },
    { id: 'B10', line: 'B', gen: 10, year: 1677, t: 340.46, kind: 'person',
      name: 'Gilbert Mangot (carpenter)',
      sub: 'b. 1677 Clermont-Ferrand',
      parents: ['B11'] },
    { id: 'SP-B10', line: 'B', gen: 10, year: 1677, t: 346.42, kind: 'spouse',
      name: 'Anne Faure',
      sub: 'm. Gilbert Mangot · Clermont-Ferrand', spouseOf: 'B10' },
    { id: 'B9',  line: 'B', gen: 9,  year: 1736, t: 352.56, kind: 'person',
      name: 'Gabriel Mangault',
      sub: 'bap. 23 Mar 1736 Saint-Pierre',
      parents: ['B10'] },
    { id: 'B8',  line: 'B', gen: 8,  year: 1773, t: 926.52, kind: 'person',
      name: 'Jean Baptiste Mongeau',
      sub: 'b. 1773 · the Auvergne–Quebec crossing',
      parents: ['B9'], candidateEdge: true },
    { id: 'B7',  line: 'B', gen: 7,  year: 1797, t: 933.74, kind: 'person',
      name: 'Jean Baptiste Mongeau dit Clermont',
      sub: 'b. 1797 · m. Catherine St-André',
      parents: ['B8'] },
    { id: 'B6',  line: 'B', gen: 6,  year: 1829, t: 1478.09, kind: 'person',
      name: 'Édouard Mongeau dit Clermont',
      sub: 'b. 1829 · m. Marie Louise Bombardier',
      parents: ['B7'] },
    { id: 'B5',  line: 'B', gen: 5,  year: 1859, t: 1940.48, kind: 'person',
      name: 'Évariste Mongeau dit Clermont',
      sub: 'm. 1878 Saint-Édouard de Napierville',
      parents: ['B6'], napierville: true },
    { id: 'B4',  line: 'B', gen: 4,  year: 1880, t: 1935.80, kind: 'person',
      name: 'Henri C. Clermont',
      sub: 'b. 1880 Saint-Liboire · crossed south 1897',
      parents: ['B5'], secondaryAnchor: true },
    { id: 'B3',  line: 'B', gen: 3,  year: 1907, t: 2111.34, kind: 'person',
      name: 'Regina Hermanise Clermont',
      sub: 'b. 1907 Williamstown, MA',
      parents: ['B4'] },

    /* ---- Line C, Bétourné (paternal) ---- */
    { id: 'C15', line: 'C', gen: 15, year: 1560, t: 158.39,  kind: 'founder',
      name: 'François Bétourné',
      sub: 'candidate · m. 1585 Saint-Crépin-Ibouvilliers',
      parents: [], candidate: true },
    { id: 'C14', line: 'C', gen: 14, year: 1575, t: 165.56,  kind: 'person',
      name: 'Jehan Bétourné',
      sub: 'about 1570s · Saint-Crépin-Ibouvilliers, Picardy',
      parents: ['C15'], candidateEdge: true },
    { id: 'C13', line: 'C', gen: 13, year: 1604, t: 173.53,  kind: 'person',
      name: 'Charles Bétourné',
      sub: 'bap. 1604 Picardy · d. 1660 Rouen',
      parents: ['C14'] },
    { id: 'SP-C13', line: 'C', gen: 13, year: 1634, t: 236.22, kind: 'spouse',
      name: 'Marguerite Bétourné',
      sub: 'm. 30 May 1634 · probably his cousin', spouseOf: 'C13' },
    { id: 'C12', line: 'C', gen: 12, year: 1635, t: 622.32, kind: 'person',
      name: 'Adrien Bétourné dit Laviolette',
      sub: 'bap. 1635 Picardy · Carignan-Salières 1665',
      parents: ['C13'] },
    { id: 'SP-C12', line: 'C', gen: 12, year: 1669, t: 646.04, kind: 'spouse',
      name: 'Marie Deshaies',
      sub: 'm. 1669 Quebec', spouseOf: 'C12' },
    { id: 'C11', line: 'C', gen: 11, year: 1669, t: 678.12, kind: 'person',
      name: 'Pierre Bétourné',
      sub: 'b. 1669 Quebec · m. 1692 Montreal',
      parents: ['C12'] },
    { id: 'SP-C11', line: 'C', gen: 11, year: 1692, t: 678.12, kind: 'spouse',
      name: 'Jeanne Françoise Ronseray',
      sub: 'm. 29 Dec 1692 Montreal', spouseOf: 'C11' },
    { id: 'C10', line: 'C', gen: 10, year: 1696, t: 809.11, kind: 'person',
      name: 'Louis Bétourné Sr.',
      sub: 'bap. 1696 Montreal · m. 1722 La Prairie',
      parents: ['C11'] },
    { id: 'SP-C10', line: 'C', gen: 10, year: 1722, t: 809.11, kind: 'spouse',
      name: 'Marguerite Dupuis',
      sub: 'm. 23 Nov 1722 La Prairie', spouseOf: 'C10' },
    { id: 'C9',  line: 'C', gen: 9,  year: 1728, t: 686.40, kind: 'person',
      name: 'Louis Bétourné',
      sub: 'bap. 1728 Longueuil',
      parents: ['C10'], candidateEdge: true },
    { id: 'C8',  line: 'C', gen: 8,  year: 1762, t: 1339.35, kind: 'person',
      name: 'Joseph Marie Bétourné',
      sub: 'b. 1762 La Prairie',
      parents: ['C9'] },
    { id: 'C7',  line: 'C', gen: 7,  year: 1793, t: 1334.65, kind: 'person',
      name: 'Toussaint Bétourné',
      sub: 'b. 1793 La Prairie',
      parents: ['C8'] },
    { id: 'C6',  line: 'C', gen: 6,  year: 1823, t: 1340.20, kind: 'person',
      name: 'Joseph Bétournay',
      sub: 'b. 1823 Saint-Philippe',
      parents: ['C7'] },
    { id: 'C5',  line: 'C', gen: 5,  year: 1854, t: 1922.52, kind: 'person',
      name: 'Modeste "Morris" Bétournay',
      sub: 'b. 1854 Napierville · crossed south 1887',
      parents: ['C6'], napierville: true },
    { id: 'C4',  line: 'C', gen: 4,  year: 1878, t: 2287.49, kind: 'person',
      name: 'Eugène Bétourney',
      sub: 'b. 1878 Saint-Joachim-de-Shefford',
      parents: ['C5'], secondaryAnchor: true },
    { id: 'C3',  line: 'C', gen: 3,  year: 1914, t: 2189.97, kind: 'person',
      name: 'Rita Marie Betourney',
      sub: 'b. 1914 North Adams, MA',
      parents: ['C4'] },

    /* ---- Line D, Heppell / Lepel (paternal) ---- */
    { id: 'D9',  line: 'D', gen: 9, year: 1690, t: 420.06, kind: 'founder',
      name: 'Philipp Jacob Heppell',
      sub: 'before 1707 · Baumholder, Rhineland', parents: [] },
    { id: 'SP-D9', line: 'D', gen: 9, year: 1690, t: 420.06, kind: 'spouse',
      name: 'Margretha',
      sub: 'Baumholder, Rhineland', spouseOf: 'D9' },
    { id: 'D8',  line: 'D', gen: 8, year: 1707, t: 440.44, kind: 'person',
      name: 'Johann Nicolaus Heppell',
      sub: 'christened 22 Jul 1707 Baumholder · surgeon',
      parents: ['D9'] },
    { id: 'SP-D8', line: 'D', gen: 8, year: 1710, t: 450.40, kind: 'spouse',
      name: 'Maria Barbara Reissen',
      sub: 'm. Johann Nicolaus · 26 Jan 1734 near Homburg', spouseOf: 'D8' },
    { id: 'D7',  line: 'D', gen: 7, year: 1750, t: 979.10, kind: 'person',
      name: 'John Jacob Jean Heppell',
      sub: 'b. 1750 Salem County, NJ · to Rimouski 1790',
      parents: ['D8'] },
    { id: 'D6',  line: 'D', gen: 6, year: 1801, t: 1208.62, kind: 'person',
      name: 'Bazile Heppell',
      sub: 'b. 1801 Rimouski',
      parents: ['D7'] },
    { id: 'D5',  line: 'D', gen: 5, year: 1845, t: 1663.42, kind: 'person',
      name: 'Napoleon Heppell',
      sub: 'b. 1845 Rimouski',
      parents: ['D6'] },
    { id: 'D4',  line: 'D', gen: 4, year: 1877, t: 1960.76, kind: 'person',
      name: 'Hermenegilde Hepel',
      sub: 'b. 1877 Saint-Ulric · crossed to Fall River 1900',
      parents: ['D5'], secondaryAnchor: true },
    { id: 'D3',  line: 'D', gen: 3, year: 1911, t: 2272.05, kind: 'person',
      name: 'Alcide J. Lepel',
      sub: 'b. 1911 Fall River, MA',
      parents: ['D4'] },
    { id: 'D2',  line: 'D', gen: 2, year: 1939, t: 2292.22, kind: 'person',
      name: 'Ronald Joseph Lepel',
      sub: 'b. 1939 Massachusetts · father',
      parents: ['UN-CD'] },


    /* ---- v3 additions: Lauzon Lepage line (E) and Bitournay/Noël ancestors ---- */
    /* Lepage line: Joseph Marie → Michel × Catherine Huard 1805 → Joseph the pit
       sawyer × Josephte Couture 1846 → Joseph the carpenter b. 1847 → Maria 1883 */
    { id: 'E11', line: 'E', gen: 11, year: 1700, t: 1229.30, kind: 'founder',
      name: 'Joseph Marie Lepage',
      sub: 'early 1700s · Lauzon (St-Joseph-de-la-Pointe-Lévy)',
      parents: [] },
    { id: 'SP-E11', line: 'E', gen: 11, year: 1700, t: 1229.30, kind: 'spouse',
      name: 'Marie Goupil',
      sub: 'early 1700s · Lauzon', spouseOf: 'E11' },
    { id: 'E10', line: 'E', gen: 10, year: 1805, t: 1236.11, kind: 'person',
      name: 'Michel Lepage',
      sub: 'm. 28 May 1805 Lauzon',
      parents: ['E11'] },
    { id: 'SP-E10', line: 'E', gen: 10, year: 1805, t: 1236.11, kind: 'spouse',
      name: 'Catherine Huard',
      sub: 'm. 1805 Lauzon', spouseOf: 'E10' },
    { id: 'E-COUTURE', line: 'E', gen: 10, year: 1808, t: 1281.62, kind: 'founder',
      name: 'Joseph Couture',
      sub: 'm. 1808 St-Henri-de-Lauzon · Maria\'s g-g-grandfather (Couture side)',
      parents: [] },
    { id: 'SP-E-COUTURE', line: 'E', gen: 10, year: 1808, t: 1281.62, kind: 'spouse',
      name: 'Marie Josèphe Blais',
      sub: 'St-Henri-de-Lauzon', spouseOf: 'E-COUTURE' },
    { id: 'E9', line: 'E', gen: 9, year: 1812, t: 1272.97, kind: 'person',
      name: 'Joseph Lepage Sr.',
      sub: 'scieur de long · Lauzon · m. 17 Feb 1846 (illiterate)',
      parents: ['E10', 'E-COUTURE'] },
    { id: 'SP-E9', line: 'E', gen: 9, year: 1812, t: 1272.97, kind: 'spouse',
      name: 'Josephte Couture',
      sub: 'm. 1846 Lauzon', spouseOf: 'E9' },
    { id: 'E8', line: 'E', gen: 8, year: 1847, t: 1316.06, kind: 'person',
      name: 'Joseph Lepage Jr. (charpentier)',
      sub: 'charpentier · b. 27 Mar 1847 Lauzon',
      parents: ['E9'] },

    /* Noël line (F): Virginia's parents and Virginia herself */
    { id: 'F-NOEL', line: 'E', gen: 9, year: 1830, t: 1536.03, kind: 'founder',
      name: 'Laurent Noël',
      sub: 'St-Michel de Bellechasse · cabotteur',
      parents: [] },
    { id: 'SP-F-NOEL', line: 'E', gen: 9, year: 1830, t: 1536.03, kind: 'spouse',
      name: 'Marguerite Duquet dit Marquette',
      sub: 'St-Michel de Bellechasse', spouseOf: 'F-NOEL' },
    { id: 'F-VIRGINIE', line: 'E', gen: 8, year: 1855, t: 1560.98, kind: 'person',
      name: 'Virginie Noël',
      sub: 'b. 23 Jul 1855 St-Michel de Bellechasse · orphan at 15',
      parents: ['F-NOEL'] },

    /* 1873 marriage: Joseph Lepage Jr × Virginie Noël */
    { id: 'UN-LEPAGE-NOEL', line: 'E', gen: 0, year: 1873, t: 1607.09, kind: 'union',
      name: 'Joseph Lepage ⚭ Virginie Noël',
      sub: '21 Jan 1873 · Notre-Dame-de-la-Victoire, Lévis',
      parents: ['E8', 'F-VIRGINIE'] },

    /* Maria Lepage (1883), Daniel's paternal great-grandmother */
    { id: 'E7-MARIA', line: 'E', gen: 7, year: 1883, t: 2046.03, kind: 'person',
      name: 'Marie Hélène Cléophée Lepage',
      sub: 'b. 19 Sep 1883 Notre-Dame de Lévis · 12 siblings · Maria Lepage in US',
      parents: ['UN-LEPAGE-NOEL'], anchor: true },

    /* Bitournay branch in Redford NY (these are Joseph Jr's parents) */
    { id: 'C-BITSR', line: 'C', gen: 5, year: 1850, t: 2012.91, kind: 'founder',
      name: 'Joseph Bitournay Sr.',
      sub: 'Redford, Clinton County, NY · before 1880',
      parents: [] },
    { id: 'SP-C-BITSR', line: 'C', gen: 5, year: 1850, t: 2012.91, kind: 'spouse',
      name: 'Elmire Rougier',
      sub: 'Redford, NY · before 1880', spouseOf: 'C-BITSR' },
    { id: 'C-BITJR', line: 'C', gen: 4, year: 1880, t: 2127.49, kind: 'person',
      name: 'Joseph Bitournay Jr. (weaver)',
      sub: 'b. 1880 Redford NY · weaver · m. Maria Lepage 1908',
      parents: ['C-BITSR'] },

    /* 1908 marriage at North Adams: Joseph Bitournay Jr × Maria Lepage */
    { id: 'UN-BIT-LEPAGE', line: 'C', gen: 0, year: 1908, t: 2136.25, kind: 'union',
      name: 'Joseph Bitournay ⚭ Maria Lepage',
      sub: '25 Aug 1908 · Notre Dame du Sacré Coeur, North Adams · Rita\'s parents',
      parents: ['C-BITJR', 'E7-MARIA'] },

    /* ---- Narrated Part 1B spouses (small side-nodes) ---- */
    { id: 'SP-NOYON', line: 'A', gen: 10, year: 1671, t: 805.16, kind: 'spouse',
      name: 'Marie Françoise de Noyon',
      sub: 'm. A10 Jean Barbeau · 1686 Boucherville',
      parents: [], spouseOf: 'A10' },
    { id: 'SP-LAVOIE-PICARD', line: 'D', gen: 99, year: 1656, t: 1157.53, kind: 'spouse',
      name: 'Pierre de la Voye dit Le Picard',
      sub: 'Picardy · crossed 1656 · Lavoie founder',
      parents: [], standalone: true },
    { id: 'SP-AGNES', line: 'D', gen: 7, year: 1769, t: 1153.09, kind: 'spouse',
      name: 'Agnès Lavoie',
      sub: 'm. D7 · 1790 Rimouski · 1st wife',
      parents: ['SP-LAVOIE-PICARD'], spouseOf: 'D7' },
    /* Victoire Bouillon — John Jacob's 2nd wife (1798).
       Per narration: the direct Heppell line ran through Victoire, not Agnès. */
    { id: 'SP-D7-VICTOIRE', line: 'D', gen: 7, year: 1775, t: 1174.28, kind: 'spouse',
      name: 'Victoire Bouillon',
      sub: 'm. D7 · 1798 Rimouski · 2nd wife · the line passed through her',
      spouseOf: 'D7', secondSpouse: true },
    { id: 'SP-BLAIS', line: 'A', gen: 5, year: 1840, t: 1754.40, kind: 'spouse',
      name: 'Marie Blais',
      sub: 'm. A5 · 1865 Napierville',
      parents: [], spouseOf: 'A5' },
    { id: 'SP-BOULERICE', line: 'B', gen: 5, year: 1859, t: 1825.14, kind: 'spouse',
      name: 'Élise Boulerisse',
      sub: 'm. B5 · 1878 Napierville',
      parents: [], spouseOf: 'B5' },
    { id: 'SP-FORGUES', line: 'A', gen: 6, year: 1810, t: 1307.57, kind: 'spouse',
      name: 'Catherine Forgues',
      sub: 'm. A6 · 1828 St-Constant',
      parents: [], spouseOf: 'A6' },

    /* ---- Unions (the trunk, 4 → 2 → 1) ---- */
    { id: 'UN-AB', line: 'TRUNK', gen: 0, year: 1931, t: 2228.81, kind: 'union',
      name: 'Regina ⚭ Ernest',
      sub: '7 Sep 1931 · Williamstown, MA',
      parents: ['B3', 'A3'] },
    { id: 'UN-CD', line: 'TRUNK', gen: 0, year: 1935, t: 2281.22, kind: 'union',
      name: 'Rita ⚭ Alcide',
      sub: '1935 · Fall River, MA',
      parents: ['C3', 'D3'] },
    { id: 'UN-FINAL', line: 'TRUNK', gen: 0, year: 1962, t: 2471.67, kind: 'union',
      name: 'Ronald ⚭ Lorraine',
      sub: 'about 1962 · North Adams · four lines become one',
      parents: ['D2', 'A2'], finalUnion: true },

    /* ---- GEN1: dimmed at opening (t=60), lit at the end (tLight=850/855) ---- */
    { id: 'GEN1-D', line: 'TRUNK', gen: 1, year: 1965, t: 2501.88, tLight: 2572.33,
      kind: 'descendant',
      name: 'Daniel Lepel',
      sub: 'b. 1965 · North Adams, MA',
      parents: ['UN-FINAL'], dimmedUntilLight: true },
    { id: 'GEN1-R', line: 'TRUNK', gen: 1, year: 1968, t: 2503.26, tLight: 2582.01,
      kind: 'descendant',
      name: 'Renée Lepel Hanson',
      sub: 'b. 1968 · North Adams, MA',
      parents: ['UN-FINAL'], dimmedUntilLight: true },

    /* ---- Ronald's brothers (Alcide & Rita's other sons) + Paul's family ---- */
    { id: 'D2-PAUL', line: 'D', gen: 2, year: 1941, t: 2385.62, kind: 'person',
      name: 'Paul A. Lepel',
      sub: 'U.S. Air Force · Elmendorf AFB, Alaska · computer programmer 23 yrs',
      parents: ['UN-CD'] },
    { id: 'D2-ROGER', line: 'D', gen: 2, year: 1945, t: 2757.30, kind: 'person',
      name: 'Roger Lepel',
      sub: 'Ronald\'s brother',
      parents: ['UN-CD'] },
    { id: 'SP-D2-PAUL', line: 'D', gen: 2, year: 1945, t: 2757.30, kind: 'spouse',
      name: 'Judy Darling',
      sub: 'm. Paul Lepel · retired in Florida',
      spouseOf: 'D2-PAUL' },
    { id: 'UN-PAUL-JUDY', line: 'D', gen: 0, year: 1968, t: 2766.26, kind: 'union',
      name: 'Paul ⚭ Judy',
      sub: 'Lepel · Darling',
      parents: ['D2-PAUL', 'SP-D2-PAUL'] },
    { id: 'GEN1-JP', line: 'TRUNK', gen: 1, year: 1969, t: 2551.38, tLight: 2766.26,
      kind: 'descendant',
      name: 'Jon Paul Lepel',
      sub: 'b. Jan 1969 · Daniel\'s cousin',
      parents: ['UN-PAUL-JUDY'], dimmedUntilLight: true },
    { id: 'GEN1-CH', line: 'TRUNK', gen: 1, year: 1974, t: 2766.26, tLight: 2770.66,
      kind: 'descendant',
      name: 'Christine Lepel',
      sub: 'b. Dec 1974 · Daniel\'s cousin',
      parents: ['UN-PAUL-JUDY'], dimmedUntilLight: true }
  ];

  /* =====================================================================
     WORLDS — dated annotations along the time ruler (canonical Part 2)
     Once revealed, they stay. The finished frame shows them all.
     ===================================================================== */
  var WORLDS = [
    /* === France: religious upheaval before the family crossings === */
    { id: 'W1562',         year: 1580, t: 118.38,
      label: 'French Wars of Religion · 1562-1598', pairWith: null,
      band: { from: 1562, to: 1598 } },
    { id: 'W1598',         year: 1598, t: 118.09,
      label: 'Edict of Nantes signed · Henri IV grants religious peace',
      pairWith: null },
    { id: 'W1608',         year: 1608, t: 206.41,
      label: 'Quebec City founded by Champlain', pairWith: null },
    { id: 'W1610',         year: 1610, t: 213.73,
      label: 'Henri IV assassinated · Louis XIII reign begins',
      pairWith: null },

    /* === Thirty Years' War: devastates the Rhineland (Heppell ancestral home) === */
    { id: 'W1618',         year: 1633, t: 373.83,
      label: 'Thirty Years\' War · 1618-1648 · devastates the Rhineland',
      pairWith: 'D9', band: { from: 1618, to: 1648 } },
    { id: 'W1642',         year: 1642, t: 480.67,
      label: 'Montreal founded', pairWith: null },
    { id: 'W1648',         year: 1648, t: 398.57,
      label: 'Peace of Westphalia ends the Thirty Years\' War',
      pairWith: null },
    { id: 'W1661',         year: 1661, t: 557.06,
      label: 'Louis XIV begins personal reign', pairWith: null },

    /* === The crossings: Carignan-Salières and the troupes de la marine === */
    { id: 'W1665',         year: 1665, t: 583.32,
      label: 'Carignan-Salières arrives · 1,200 soldiers',
      pairWith: 'C12' },
    { id: 'W1666',         year: 1666, t: 642.34,
      label: 'Mohawk campaigns', pairWith: null },
    { id: 'W1668',         year: 1668, t: 650.66,
      label: 'Regiment disbanded · ~400 stay', pairWith: null },
    { id: 'W1672',         year: 1675, t: 682.13,
      label: 'Franco-Dutch War · 1672-1678', pairWith: null,
      band: { from: 1672, to: 1678 } },
    { id: 'W1685-edit',    year: 1685, t: 732.17,
      label: 'Revocation of the Edict of Nantes · Protestantism outlawed',
      pairWith: 'A10' },
    { id: 'W1685-denon',   year: 1685, t: 718.96,
      label: 'Denonville · troupes de la marine', pairWith: 'A10' },

    /* === Late 17th to mid-18th century: Quebec consolidates, France wars === */
    { id: 'W1701',         year: 1701, t: 867.99,
      label: 'Great Peace of Montreal with First Nations',
      pairWith: null },
    { id: 'W1701s',        year: 1707, t: 880.74,
      label: 'War of Spanish Succession · Queen Anne\'s War · 1701-1714',
      pairWith: null, band: { from: 1701, to: 1714 } },
    { id: 'W1709',         year: 1709, t: 892.78,
      label: 'Le Grand Hiver · the Great Famine devastates France',
      pairWith: null },
    { id: 'W1713',         year: 1713, t: 903.42,
      label: 'Treaty of Utrecht · Britain gains Acadia and Newfoundland',
      pairWith: null },
    { id: 'W1740',         year: 1744, t: 948.87,
      label: 'War of Austrian Succession · King George\'s War · 1740-1748',
      pairWith: null, band: { from: 1740, to: 1748 } },

    /* === The Conquest: French and Indian War, fall of New France === */
    { id: 'W1755',         year: 1755, t: 1019.63,
      label: 'Acadian Expulsion · Le Grand Dérangement',
      pairWith: null },
    { id: 'W1756',         year: 1759, t: 1033.35,
      label: 'Seven Years\' War · French and Indian War · 1756-1763',
      pairWith: null, band: { from: 1756, to: 1763 } },
    { id: 'W1759',         year: 1759, t: 1050.03,
      label: 'Battle of the Plains of Abraham · Quebec falls',
      pairWith: null },
    { id: 'W1763',         year: 1763, t: 1064.02,
      label: 'Treaty of Paris · New France ceded to Britain',
      pairWith: 'A7' },
    { id: 'W1774',         year: 1774, t: 1101.91,
      label: 'Quebec Act preserves French civil law and Catholic religion',
      pairWith: null },

    /* === Revolutions and the long 19th century === */
    { id: 'W1775',         year: 1779, t: 1121.06,
      label: 'American Revolution · 1775-1783', pairWith: null,
      band: { from: 1775, to: 1783 } },
    { id: 'W1789',         year: 1794, t: 1346.60,
      label: 'French Revolution · 1789-1799', pairWith: null,
      band: { from: 1789, to: 1799 } },
    { id: 'W1803',         year: 1809, t: 1364.86,
      label: 'Napoleonic Wars · 1803-1815', pairWith: null,
      band: { from: 1803, to: 1815 } },
    { id: 'W1837',         year: 1838, t: 1446.49,
      label: 'Lower Canada Rebellion · 1837-1838', pairWith: null },
    { id: 'W1840-1930',    year: 1885, t: 1900.09,
      label: 'French-Canadian mill migration · 1840-1930 · ~900,000',
      pairWith: null, band: { from: 1840, to: 1930 } },

    /* === Confederation, the Franco-Prussian War, the modern era === */
    { id: 'W1867',         year: 1867, t: 1859.84,
      label: 'Canadian Confederation', pairWith: null },
    { id: 'W1870',         year: 1871, t: 1871.32,
      label: 'Franco-Prussian War · German Empire founded · 1870-1871',
      pairWith: null, band: { from: 1870, to: 1871 } },
    { id: 'W1914',         year: 1916, t: 2195.05,
      label: 'World War I · 1914-1918', pairWith: null,
      band: { from: 1914, to: 1918 } },
    { id: 'W1929',         year: 1932, t: 2228.46,
      label: 'Great Depression · 1929-1939', pairWith: null,
      band: { from: 1929, to: 1939 } },
    { id: 'W1939',         year: 1942, t: 2299.56,
      label: 'World War II · 1939-1945', pairWith: null,
      band: { from: 1939, to: 1945 } },
    { id: 'W2025',         year: 2025, t: 2562.67,
      label: 'Bill C-3 takes effect · 15 December 2025',
      pairWith: 'A4' }
  ];

  /* =====================================================================
     MIGRATIONS — map ARROWs. Each opens a map-inset surface window of
     [t, t + tHold]. The inset slides in, holds, slides out.
     ===================================================================== */
  var MIGRATIONS = [
    /* === Crossings (arrows) — each fires AT the beat that narrates it === */
    { id: 'M-adrien',   t: 616.11,  tHold: 22,
      label: '1665 · Adrien Bétourné · Picardy → Quebec',
      line: 'C', from: [49.42, 1.94],  to: [46.81, -71.21] },
    { id: 'M-jean',     t: 757.78,  tHold: 28,
      label: '1685 · Jean Barbeau · Pons → Quebec',
      line: 'A', from: [45.58, -0.55], to: [45.59, -73.45] },
    { id: 'M-mongeau',  t: 912.70,  tHold: 22,
      label: 'After 1736 · Mongeau · Auvergne → Quebec',
      line: 'B', from: [45.78, 3.08],  to: [45.59, -73.45],
      candidate: true },
    { id: 'M-heppell',  t: 977.88,  tHold: 22,
      label: 'Heppell · Rhineland → New Jersey',
      line: 'D', from: [49.61, 7.34],  to: [39.57, -75.46] },
    { id: 'M-johnjacob', t: 1002.87, tHold: 22,
      label: '1790 · John Jacob Heppell · New Jersey → Rimouski',
      line: 'D', from: [39.57, -75.46], to: [48.45, -68.52] },
    { id: 'M-modeste',  t: 1895.81,  tHold: 22,
      label: 'French-Canadian mill migration · Quebec → New England',
      line: 'C', from: [45.32, -73.41], to: [42.70, -73.11] },
    { id: 'M-henri',    t: 2058.29,  tHold: 22,
      label: '1897 · Henri Clermont · Quebec → Berkshires',
      line: 'B', from: [45.65, -72.78], to: [42.72, -73.20] },
    { id: 'M-hermenegilde', t: 2097.56, tHold: 22,
      label: '1900 · Hermenegilde Hepel · Quebec → Fall River',
      line: 'D', from: [48.78, -67.72], to: [41.70, -71.16] },
    { id: 'M-daniel',   t: 2550.70,  tHold: 16,
      label: 'Daniel · North Adams → Albany, NY',
      line: 'TRUNK', from: [42.70, -73.11], to: [42.65, -73.76] },

    /* === Single-point location pins (no arrow) — fire WHEN each region is
       first named in the narration, not before. */
    { id: 'L-stlawrence', t: 138.31, tHold: 18, line: 'TRUNK', isLocation: true,
      label: 'Saint Lawrence · Champlain\'s maps · 1603',
      from: [46.81, -71.21], to: null },
    { id: 'L-picardy',     t: 154.00, tHold: 22, line: 'C', isLocation: true,
      label: 'Picardy · Saint-Crépin-Ibouvilliers',
      from: [49.42, 1.94], to: null },
    { id: 'L-quebec',      t: 203.83, tHold: 14, line: 'TRUNK', isLocation: true,
      label: 'Quebec City founded · 1608',
      from: [46.81, -71.21], to: null },
    { id: 'L-rouen',       t: 244.96, tHold: 14, line: 'C', isLocation: true,
      label: 'Rouen · Charles Bétourné died here · 1660',
      from: [49.44, 1.10], to: null },
    { id: 'L-auvergne',    t: 298.71, tHold: 22, line: 'B', isLocation: true,
      label: 'Auvergne · Clermont-Ferrand',
      from: [45.78, 3.08], to: null },
    { id: 'L-rhineland',   t: 413.03, tHold: 22, line: 'D', isLocation: true,
      label: 'Rhineland · Baumholder',
      from: [49.61, 7.34], to: null },
    { id: 'L-saintonge',   t: 477.97, tHold: 22, line: 'A', isLocation: true,
      label: 'Saintonge · Pons',
      from: [45.58, -0.55], to: null }
  ];

  /* =====================================================================
     BEATS — the 40-beat cue sheet. Used for caption display and as the
     camera-walk anchor list. Re-lock .t to the final audio later.
     ===================================================================== */
  var BEATS = [
    { t: 0.00,    narration: 'Every living person is the survivor of an unbroken line.', focus: null },
    { t: 31.05,   narration: 'Now and then, a few of those branches can still be followed.', focus: null },
    { t: 54.29,   narration: 'Four lines of descent, across four countries and more than four centuries.', focus: 'RULER' },
    { t: 64.89,   narration: 'It begins in 1604, in a village in the north of France.', focus: 'RULER' },
    { t: 93.50,   narration: 'And then, four separate families become one.', focus: 'GEN1-D' },
    { t: 163.50,   narration: 'Jehan Bétourné carried his newborn son to the parish church to be baptised.', focus: 'C14' },
    { t: 170.72,   narration: 'The child was named Charles Bétourné.',                                       focus: 'C13' },
    { t: 236.22,   narration: 'Married Marguerite. Died at Rouen in 1660.',                                  focus: 'SP-C13' },
    { t: 299.27,  narration: 'In Clermont-Ferrand, a Catholic family named Mangot worshipped at Saint-Pierre.', focus: 'B12' },
    { t: 305.59,  narration: 'The deepest of them is Mathieu Mangot.',                                      focus: 'B12' },
    { t: 316.04,  narration: 'They were carpenters. The family stayed for four documented generations.',    focus: 'B11' },
    { t: 350.07,  narration: 'Gabriel Mangault baptised 23 March 1736, at five o’clock in the morning.', focus: 'B9' },
    { t: 413.57,  narration: 'In the Rhineland, the Heppells lived as German Lutherans near Baumholder.',   focus: 'D9' },
    { t: 419.31,  narration: 'Philipp Jacob Heppell and Margretha raised their children there.',            focus: 'D9' },
    { t: 440.44,  narration: 'Their son Johann Nicolaus Heppell was baptised 22 July 1707.',                focus: 'D8' },
    { t: 478.31,  narration: 'In Saintonge, Pierre Barbeau and Madeleine Babin were raising a family.',    focus: 'A11' },
    { t: 494.59,  narration: 'In 1666 they had a son named Jean.',                                          focus: 'A10' },
    { t: 510.56,  narration: 'These four European families would all eventually send descendants to one mill town.', focus: null },
    { t: 582.28,  narration: 'The Carignan-Salières Regiment disembarked at Quebec City.',                  focus: 'W1665' },
    { t: 619.90,  narration: 'Among the soldiers was Adrien Bétourné.',                                     focus: 'C12' },
    { t: 646.04,  narration: 'Campaigns against the Mohawk. Disbanded 1668. Married Marie Deshaies 1669.', focus: 'C12' },
    { t: 705.92,  narration: 'Twenty years later, a second soldier crossed.',                               focus: 'RULER' },
    { t: 722.18,  narration: 'Troupes de la marine sailed with the marquis de Denonville.',                 focus: 'W1685-denon' },
    { t: 731.30,  narration: 'Louis XIV revoked the Edict of Nantes.',                                      focus: 'W1685-edit' },
    { t: 760.30,  narration: 'He was Jean Barbeau, the merchant’s son. Nickname: Boisdoré.',           focus: 'A10' },
    { t: 803.99,  narration: 'Married Marie Françoise de Noyon, 18 November 1686, Boucherville.',           focus: 'A10' },
    { t: 830.89,  narration: 'Through their son Gabriel, baptised 1694; Gabriel’s son Jean-Baptiste, 1725.', focus: 'A9' },
    { t: 913.24,  narration: 'In Auvergne, the Mangot carpenters became Mongeau dit Clermont.',             focus: 'B8' },
    { t: 978.30,  narration: 'The Heppells crossed. John Jacob Jean Heppell born 1750, New Jersey.',       focus: 'D7' },
    { t: 993.97,  narration: 'Joseph Barbeau dit Boisdoré baptised at Saint-Constant in 1757.',             focus: 'A7' },
    { t: 1003.62,  narration: 'John Jacob Heppell married Agnès Lavoie 1790, Rimouski.',                    focus: 'SP-AGNES' },
    { t: 1006.27,  narration: 'Pierre de la Voye dit Le Picard had crossed in 1656.',                        focus: 'SP-LAVOIE-PICARD' },
    { t: 1058.17,  narration: 'Six years old when the Treaty of Paris handed New France to Britain.',        focus: 'W1763' },
    { t: 1118.63,  narration: 'In 1775 the American Revolution broke out.',                                  focus: 'W1775' },
    { t: 1200.22,  narration: 'The surname slid from Heppell to Epelle to Hepel.',                           focus: 'D7' },
    /* Lepage line — was previously narrated without camera focus, so the
       column never appeared on screen. */
    { t: 1224.88,  narration: 'In Lauzon, on the south shore of the Saint Lawrence, the Lepage line begins.', focus: 'E11' },
    { t: 1238.12,  narration: 'Michel Lepage married Catherine Huard at Lauzon, 1805.',                       focus: 'E10' },
    { t: 1271.90,  narration: 'Joseph Lepage the pit sawyer married Josephte Couture, 1846.',                 focus: 'E9' },
    { t: 1316.06,  narration: 'Joseph Lepage Jr., charpentier — their son.',                                  focus: 'E8' },
    { t: 1405.44,  narration: 'François Régis Barbeau born at Saint-Constant in 1804. M. Catherine Forgues 1828.', focus: 'A6' },
    { t: 1465.36,  narration: 'By the early 1800s the old nicknames were fading.',                           focus: 'A7' },
    { t: 1536.03,  narration: 'In Saint-Michel de Bellechasse, Laurent Noel and Marguerite Duquet.',          focus: 'F-NOEL' },
    { t: 1560.98,  narration: 'Virginie Noel, baptised 1855, orphan at fifteen.',                             focus: 'F-VIRGINIE' },
    { t: 1607.09,  narration: 'Joseph Lepage Jr. married Virginie Noel, 1873, at Notre-Dame-de-la-Victoire.', focus: 'UN-LEPAGE-NOEL' },
    { t: 1752.27,  narration: 'Magloire Barbeau married Marie Blais, 1865.',                                 focus: 'A5' },
    { t: 1768.32,  narration: 'Joseph Wilfred Barbeau baptised 1870. The documentary anchor for Bill C-3.',  focus: 'A4' },
    { t: 1772.24,  narration: 'At Saint-Édouard de Napierville, three lines were converging.',               focus: 'C5' },
    { t: 1895.99,  narration: 'The mills called. Roughly 900,000 French-Canadians left Quebec.',             focus: 'W1840-1930' },
    { t: 2046.03,  narration: 'Marie Helene Cleophee Lepage, b. 1883 — Daniel\'s paternal great-grandmother.', focus: 'E7-MARIA' },
    { t: 2073.87,  narration: 'All four lines were converging on the Berkshire Hills.',                      focus: null },
    { t: 2180.34,  narration: 'Rita Betourney born 1914. Alcide Lepel born 1911. They married.',             focus: 'UN-CD' },
    { t: 2230.37,  narration: 'Ernest Barbeau and Regina Clermont married 1931.',                            focus: 'UN-AB' },
    { t: 2471.67,  narration: 'Ronald Joseph Lepel married Lorraine Irene Barbeau. The four lines became one.', focus: 'UN-FINAL' },
    { t: 2501.88,  narration: 'Daniel and Renee grew up in North Adams. Daniel moved to Albany.',            focus: 'GEN1-D' },
    { t: 2551.38,  narration: 'Jon Lepel lives in the same state.',                                           focus: 'GEN1-JP' },
    { t: 2563.63,  narration: 'Bill C-3 took effect, 15 December 2025.',                                     focus: 'W2025' },
    { t: 2586.12,  narration: 'The research reached back four hundred and twenty-two years.',                focus: 'OVERVIEW' },
    { t: 2617.11,  narration: 'Traced the Barbeau line back to a merchant house in Pons.',                  focus: 'A11', highlight: 'A' },
    { t: 2746.19,  narration: 'This is who they came from. This is how they got here.',                      focus: 'OVERVIEW' },
    { t: 2757.30,  narration: 'Ronald had two brothers: Paul and Roger.',                                     focus: 'DESCENDANTS' },
    { t: 2772.00,  narration: 'Aunt Judy is still living, retired in Florida.',                              focus: 'DESCENDANTS' }
  ];

  /* CONFIG: surfaces the time-axis range so the engine and ruler share
     identical year-to-x math. */
  var TIME = { yearMin: 1600, yearMax: 2030 };

  window.LINEAGE_DATA = {
    LINES: LINES,
    PEOPLE: PEOPLE,
    WORLDS: WORLDS,
    MIGRATIONS: MIGRATIONS,
    BEATS: BEATS,
    TIME: TIME
  };
})();
