/* =====================================================================
   Lineage V2 — DATA LAYER  (single source of truth)
   --------------------------------------------------------------------
   PEOPLE        — every narrated ancestor as a node with stable canonical
                   ID (A11..GEN1 / B12..GEN1 / C15..GEN1 / D9..GEN1).
   WORLDS        — dated world-event annotations along the time ruler.
   MIGRATIONS    — map ARROWs and the windows the map inset surfaces in.
   BEATS         — the 40-beat narration cue sheet (provisional t).
                   Re-lock Time column to the final ElevenLabs audio by
                   editing only the .t values here. Order and tree cues
                   never change; only the seconds do.
   --------------------------------------------------------------------
   Source files:
     Lineage_Canonical_Timeline_2026-05-25.md      (Part 1, 1B, 2)
     Lineage_Narration_Timestamps_2026-05-25.md    (the 40-beat cue sheet)
   All times in audio-seconds.
   ===================================================================== */
(function () {
  'use strict';

  /* ----- the four lineages (column order: merging pairs adjacent) ----- */
  var LINES = [
    { id: 'C', label: 'Bétourné dit Laviolette', origin: 'Picardy, France',
      color: 'var(--c-betourne)' },
    { id: 'D', label: 'Heppell · Lepel',          origin: 'Rhineland, Prussia',
      color: 'var(--c-heppell)' },
    { id: 'B', label: 'Mongeau dit Clermont',     origin: 'Auvergne, France',
      color: 'var(--c-mongeau)' },
    { id: 'A', label: 'Barbeau dit Boisdoré',     origin: 'Saintonge, France',
      color: 'var(--c-barbeau)' },

    { id: 'E', label: 'Lepage · Noël',         origin: 'Lauzon / Bellechasse, Quebec',
      color: 'var(--c-lepage, #b89967)' }
  ];

  /* =====================================================================
     PEOPLE — canonical Part 1 (full depth) + narrated Part 1B spouses
     Each: { id, line, gen, year, name, sub, parents, kind, t, ...flags }
     kind: 'person' | 'founder' | 'spouse' | 'union' | 'descendant'
     flags: anchor, candidate, dimmedUntil, tLight, napierville, finalUnion
     ===================================================================== */
  var PEOPLE = [

    /* ---- Line A, Barbeau (maternal) ---- */
    { id: 'A11', line: 'A', gen: 11, year: 1660, t: 500.96, kind: 'founder',
      name: 'Pierre Barbeau',
      sub: 'Pons, Saintonge · merchant family', parents: [] },
    { id: 'SP-A11', line: 'A', gen: 11, year: 1660, t: 500.96, kind: 'spouse',
      name: 'Madeleine Babin',
      sub: 'Pons, Saintonge', spouseOf: 'A11' },
    { id: 'A10', line: 'A', gen: 10, year: 1666, t: 875.33, kind: 'person',
      name: 'Jean Barbeau dit Boisdoré',
      sub: 'b. 1666 Pons · soldier of the King 1685',
      parents: ['A11'] },
    { id: 'A9',  line: 'A', gen: 9,  year: 1694, t: 941.32, kind: 'person',
      name: 'Gabriel Barbeau dit Boisdoré',
      sub: 'bap. 1694 Boucherville',
      parents: ['A10'] },
    { id: 'A8',  line: 'A', gen: 8,  year: 1725, t: 941.52, kind: 'person',
      name: 'Jean-Baptiste Barbeau dit Boisdoré',
      sub: 'bap. 1725 La Prairie',
      parents: ['A9'] },
    { id: 'A7',  line: 'A', gen: 7,  year: 1757, t: 1105.74, kind: 'person',
      name: 'Joseph Barbeau dit Boisdoré',
      sub: 'bap. 1757 Saint-Constant',
      parents: ['A8'] },
    { id: 'A6',  line: 'A', gen: 6,  year: 1804, t: 1543.24, kind: 'person',
      name: 'François Régis Barbeau',
      sub: 'b. 1804 Saint-Constant · m. 1828',
      parents: ['A7'] },
    { id: 'A5',  line: 'A', gen: 5,  year: 1833, t: 1884.7, kind: 'person',
      name: 'Magloire Barbeau',
      sub: 'b. 1833 Saint-Philippe · m. 1865 Napierville',
      parents: ['A6'], napierville: true },
    { id: 'A4',  line: 'A', gen: 4,  year: 1870, t: 1884.9, kind: 'person',
      name: 'Joseph Wilfred Barbeau',
      sub: 'b. 1870 Napierville · Bill C-3 anchor',
      parents: ['A5'], anchor: true, napierville: true },
    { id: 'A3',  line: 'A', gen: 3,  year: 1906, t: 2242.54, kind: 'person',
      name: 'Rouville Ernest Barbeau',
      sub: 'b. 1906 North Adams, MA',
      parents: ['A4'] },
    { id: 'A2',  line: 'A', gen: 2,  year: 1943, t: 2388.76, kind: 'person',
      name: 'Lorraine Irene Barbeau',
      sub: 'b. 1943 North Adams · mother',
      parents: ['UN-AB'] },

    /* ---- Line B, Clermont / Mongeau (maternal) ---- */
    { id: 'B12', line: 'B', gen: 12, year: 1615, t: 328.32, kind: 'founder',
      name: 'Mathieu Mangot',
      sub: 'near Clermont-Ferrand, Auvergne', parents: [] },
    { id: 'SP-B12', line: 'B', gen: 12, year: 1615, t: 328.32, kind: 'spouse',
      name: 'Marguerite Blandette',
      sub: 'Clermont-Ferrand', spouseOf: 'B12' },
    { id: 'B11', line: 'B', gen: 11, year: 1643, t: 346.28, kind: 'person',
      name: 'Antoine Mangot',
      sub: 'bap. 1643 Saint-Pierre, Clermont-Ferrand',
      parents: ['B12'] },
    { id: 'SP-B11', line: 'B', gen: 11, year: 1643, t: 360.54, kind: 'spouse',
      name: 'Gabrielle Pabiot',
      sub: 'Clermont-Ferrand', spouseOf: 'B11' },
    { id: 'B10', line: 'B', gen: 10, year: 1677, t: 363.72, kind: 'person',
      name: 'Gilbert Mangot (carpenter)',
      sub: 'b. 1677 Clermont-Ferrand',
      parents: ['B11'] },
    { id: 'SP-B10', line: 'B', gen: 10, year: 1677, t: 369.72, kind: 'spouse',
      name: 'Anne Faure',
      sub: 'm. Gilbert Mangot · Clermont-Ferrand', spouseOf: 'B10' },
    { id: 'B9',  line: 'B', gen: 9,  year: 1736, t: 373.1, kind: 'person',
      name: 'Gabriel Mangault',
      sub: 'bap. 23 Mar 1736 Saint-Pierre',
      parents: ['B10'] },
    { id: 'B8',  line: 'B', gen: 8,  year: 1773, t: 1330.02, kind: 'person',
      name: 'Jean Baptiste Mongeau',
      sub: 'b. 1773 · the Auvergne–Quebec crossing',
      parents: ['B9'], candidateEdge: true },
    { id: 'B7',  line: 'B', gen: 7,  year: 1797, t: 1485.55, kind: 'person',
      name: 'Jean Baptiste Mongeau dit Clermont',
      sub: 'b. 1797 · m. Catherine St-André',
      parents: ['B8'] },
    { id: 'B6',  line: 'B', gen: 6,  year: 1829, t: 1959, kind: 'person',
      name: 'Édouard Mongeau dit Clermont',
      sub: 'b. 1829 · m. Marie Louise Bombardier',
      parents: ['B7'] },
    { id: 'B5',  line: 'B', gen: 5,  year: 1859, t: 1959.2, kind: 'person',
      name: 'Évariste Mongeau dit Clermont',
      sub: 'm. 1878 Saint-Édouard de Napierville',
      parents: ['B6'], napierville: true },
    { id: 'B4',  line: 'B', gen: 4,  year: 1880, t: 2079.88, kind: 'person',
      name: 'Henri C. Clermont',
      sub: 'b. 1880 Saint-Liboire · crossed south 1897',
      parents: ['B5'], secondaryAnchor: true },
    { id: 'B3',  line: 'B', gen: 3,  year: 1907, t: 2249.45, kind: 'person',
      name: 'Regina Hermanise Clermont',
      sub: 'b. 1907 Williamstown, MA',
      parents: ['B4'] },

    /* ---- Line C, Bétourné (paternal) ---- */
    { id: 'C15', line: 'C', gen: 15, year: 1560, t: 155.12,  kind: 'founder',
      name: 'François Bétourné',
      sub: 'candidate · m. 1585 Saint-Crépin-Ibouvilliers',
      parents: [], candidate: true },
    { id: 'C14', line: 'C', gen: 14, year: 1575, t: 171.64,  kind: 'person',
      name: 'Jehan Bétourné',
      sub: 'about 1570s · Saint-Crépin-Ibouvilliers, Picardy',
      parents: ['C15'], candidateEdge: true },
    { id: 'C13', line: 'C', gen: 13, year: 1604, t: 188.94,  kind: 'person',
      name: 'Charles Bétourné',
      sub: 'bap. 1604 Picardy · d. 1660 Rouen',
      parents: ['C14'] },
    { id: 'SP-C13', line: 'C', gen: 13, year: 1634, t: 253.88, kind: 'spouse',
      name: 'Marguerite Bétourné',
      sub: 'm. 30 May 1634 · probably his cousin', spouseOf: 'C13' },
    { id: 'C12', line: 'C', gen: 12, year: 1635, t: 293.18, kind: 'person',
      name: 'Adrien Bétourné dit Laviolette',
      sub: 'bap. 1635 Picardy · Carignan-Salières 1665',
      parents: ['C13'] },
    { id: 'SP-C12', line: 'C', gen: 12, year: 1669, t: 749.89, kind: 'spouse',
      name: 'Marie Deshaies',
      sub: 'm. 1669 Quebec', spouseOf: 'C12' },
    { id: 'C11', line: 'C', gen: 11, year: 1669, t: 807.64, kind: 'person',
      name: 'Pierre Bétourné',
      sub: 'b. 1669 Quebec · m. 1692 Montreal',
      parents: ['C12'] },
    { id: 'SP-C11', line: 'C', gen: 11, year: 1692, t: 933.84, kind: 'spouse',
      name: 'Jeanne Françoise Ronseray',
      sub: 'm. 29 Dec 1692 Montreal', spouseOf: 'C11' },
    { id: 'C10', line: 'C', gen: 10, year: 1696, t: 949.42, kind: 'person',
      name: 'Louis Bétourné Sr.',
      sub: 'bap. 1696 Montreal · m. 1722 La Prairie',
      parents: ['C11'] },
    { id: 'SP-C10', line: 'C', gen: 10, year: 1722, t: 1298.51, kind: 'spouse',
      name: 'Marguerite Dupuis',
      sub: 'm. 23 Nov 1722 La Prairie', spouseOf: 'C10' },
    { id: 'C9',  line: 'C', gen: 9,  year: 1728, t: 1330.02, kind: 'person',
      name: 'Louis Bétourné',
      sub: 'bap. 1728 Longueuil',
      parents: ['C10'], candidateEdge: true },
    { id: 'C8',  line: 'C', gen: 8,  year: 1762, t: 2420.86, kind: 'person',
      name: 'Joseph Marie Bétourné',
      sub: 'b. 1762 La Prairie',
      parents: ['C9'] },
    { id: 'C7',  line: 'C', gen: 7,  year: 1793, t: 2421.06, kind: 'person',
      name: 'Toussaint Bétourné',
      sub: 'b. 1793 La Prairie',
      parents: ['C8'] },
    { id: 'C6',  line: 'C', gen: 6,  year: 1823, t: 2421.26, kind: 'person',
      name: 'Joseph Bétournay',
      sub: 'b. 1823 Saint-Philippe',
      parents: ['C7'] },
    { id: 'C5',  line: 'C', gen: 5,  year: 1854, t: 2421.46, kind: 'person',
      name: 'Modeste "Morris" Bétournay',
      sub: 'b. 1854 Napierville · crossed south 1887',
      parents: ['C6'], napierville: true },
    { id: 'C4',  line: 'C', gen: 4,  year: 1878, t: 2421.66, kind: 'person',
      name: 'Eugène Bétourney',
      sub: 'b. 1878 Saint-Joachim-de-Shefford',
      parents: ['C5'], secondaryAnchor: true },
    { id: 'C3',  line: 'C', gen: 3,  year: 1914, t: 2421.86, kind: 'person',
      name: 'Rita Marie Betourney',
      sub: 'b. 1914 North Adams, MA',
      parents: ['C4'] },

    /* ---- Line D, Heppell / Lepel (paternal) ---- */
    { id: 'D9',  line: 'D', gen: 9, year: 1690, t: 446.1, kind: 'founder',
      name: 'Philipp Jacob Heppell',
      sub: 'before 1707 · Baumholder, Rhineland', parents: [] },
    { id: 'SP-D9', line: 'D', gen: 9, year: 1690, t: 446.1, kind: 'spouse',
      name: 'Margretha',
      sub: 'Baumholder, Rhineland', spouseOf: 'D9' },
    { id: 'D8',  line: 'D', gen: 8, year: 1707, t: 465.78, kind: 'person',
      name: 'Johann Nicolaus Heppell',
      sub: 'christened 22 Jul 1707 Baumholder · surgeon',
      parents: ['D9'] },
    { id: 'SP-D8', line: 'D', gen: 8, year: 1710, t: 473.67, kind: 'spouse',
      name: 'Maria Barbara Reissen',
      sub: 'm. Johann Nicolaus · 26 Jan 1734 near Homburg', spouseOf: 'D8' },
    { id: 'D7',  line: 'D', gen: 7, year: 1750, t: 1085.7, kind: 'person',
      name: 'John Jacob Jean Heppell',
      sub: 'b. 1750 Salem County, NJ · to Rimouski 1790',
      parents: ['D8'] },
    { id: 'D6',  line: 'D', gen: 6, year: 1801, t: 1491.59, kind: 'person',
      name: 'Bazile Heppell',
      sub: 'b. 1801 Rimouski',
      parents: ['D7'] },
    { id: 'D5',  line: 'D', gen: 5, year: 1845, t: 2044.93, kind: 'person',
      name: 'Napoleon Heppell',
      sub: 'b. 1845 Rimouski',
      parents: ['D6'] },
    { id: 'D4',  line: 'D', gen: 4, year: 1877, t: 2107.12, kind: 'person',
      name: 'Hermenegilde Hepel',
      sub: 'b. 1877 Saint-Ulric · crossed to Fall River 1900',
      parents: ['D5'], secondaryAnchor: true },
    { id: 'D3',  line: 'D', gen: 3, year: 1911, t: 2409.82, kind: 'person',
      name: 'Alcide J. Lepel',
      sub: 'b. 1911 Fall River, MA',
      parents: ['D4'] },
    { id: 'D2',  line: 'D', gen: 2, year: 1939, t: 2434.38, kind: 'person',
      name: 'Ronald Joseph Lepel',
      sub: 'b. 1939 Massachusetts · father',
      parents: ['UN-CD'] },


    /* ---- v3 additions: Lauzon Lepage line (E) and Bitournay/Noël ancestors ---- */
    /* Lepage line: Joseph Marie → Michel × Catherine Huard 1805 → Joseph the pit
       sawyer × Josephte Couture 1846 → Joseph the carpenter b. 1847 → Maria 1883 */
    { id: 'E11', line: 'E', gen: 11, year: 1700, t: 1330.02, kind: 'founder',
      name: 'Joseph Marie Lepage',
      sub: 'early 1700s · Lauzon (St-Joseph-de-la-Pointe-Lévy)',
      parents: [] },
    { id: 'SP-E11', line: 'E', gen: 11, year: 1700, t: 1330.02, kind: 'spouse',
      name: 'Marie Goupil',
      sub: 'early 1700s · Lauzon', spouseOf: 'E11' },
    { id: 'E10', line: 'E', gen: 10, year: 1805, t: 1375.66, kind: 'person',
      name: 'Michel Lepage',
      sub: 'm. 28 May 1805 Lauzon',
      parents: ['E11'] },
    { id: 'SP-E10', line: 'E', gen: 10, year: 1805, t: 1495.96, kind: 'spouse',
      name: 'Catherine Huard',
      sub: 'm. 1805 Lauzon', spouseOf: 'E10' },
    { id: 'E-COUTURE', line: 'E', gen: 10, year: 1808, t: 1400.92, kind: 'founder',
      name: 'Joseph Couture',
      sub: 'm. 1808 St-Henri-de-Lauzon · Maria\'s g-g-grandfather (Couture side)',
      parents: [] },
    { id: 'SP-E-COUTURE', line: 'E', gen: 10, year: 1808, t: 1400.92, kind: 'spouse',
      name: 'Marie Josèphe Blais',
      sub: 'St-Henri-de-Lauzon', spouseOf: 'E-COUTURE' },
    { id: 'E9', line: 'E', gen: 9, year: 1812, t: 1495.96, kind: 'person',
      name: 'Joseph Lepage Sr.',
      sub: 'scieur de long · Lauzon · m. 17 Feb 1846 (illiterate)',
      parents: ['E10', 'E-COUTURE'] },
    { id: 'SP-E9', line: 'E', gen: 9, year: 1812, t: 1400.92, kind: 'spouse',
      name: 'Josephte Couture',
      sub: 'm. 1846 Lauzon', spouseOf: 'E9' },
    { id: 'E8', line: 'E', gen: 8, year: 1847, t: 1814.06, kind: 'person',
      name: 'Joseph Lepage Jr. (charpentier)',
      sub: 'charpentier · b. 27 Mar 1847 Lauzon',
      parents: ['E9'] },

    /* Noël line (F): Virginia's parents and Virginia herself */
    { id: 'F-NOEL', line: 'E', gen: 9, year: 1830, t: 1676.74, kind: 'founder',
      name: 'Laurent Noël',
      sub: 'St-Michel de Bellechasse · cabotteur',
      parents: [] },
    { id: 'SP-F-NOEL', line: 'E', gen: 9, year: 1830, t: 1692.82, kind: 'spouse',
      name: 'Marguerite Duquet dit Marquette',
      sub: 'St-Michel de Bellechasse', spouseOf: 'F-NOEL' },
    { id: 'F-VIRGINIE', line: 'E', gen: 8, year: 1855, t: 1706.52, kind: 'person',
      name: 'Virginie Noël',
      sub: 'b. 23 Jul 1855 St-Michel de Bellechasse · orphan at 15',
      parents: ['F-NOEL'] },

    /* 1873 marriage: Joseph Lepage Jr × Virginie Noël */
    { id: 'UN-LEPAGE-NOEL', line: 'E', gen: 0, year: 1873, t: 2072.89, kind: 'union',
      name: 'Joseph Lepage ⚭ Virginie Noël',
      sub: '21 Jan 1873 · Notre-Dame-de-la-Victoire, Lévis',
      parents: ['E8', 'F-VIRGINIE'] },

    /* Maria Lepage (1883), Daniel's paternal great-grandmother */
    { id: 'E7-MARIA', line: 'E', gen: 7, year: 1883, t: 1814.06, kind: 'person',
      name: 'Marie Hélène Cléophée Lepage',
      sub: 'b. 19 Sep 1883 Notre-Dame de Lévis · 12 siblings · Maria Lepage in US',
      parents: ['UN-LEPAGE-NOEL'], anchor: true },

    /* Bitournay branch in Redford NY (these are Joseph Jr's parents) */
    { id: 'C-BITSR', line: 'C', gen: 5, year: 1850, t: 2049.93, kind: 'founder',
      name: 'Joseph Bitournay Sr.',
      sub: 'Redford, Clinton County, NY · before 1880',
      parents: [] },
    { id: 'SP-C-BITSR', line: 'C', gen: 5, year: 1850, t: 2155, kind: 'spouse',
      name: 'Elmire Rougier',
      sub: 'Redford, NY · before 1880', spouseOf: 'C-BITSR' },
    { id: 'C-BITJR', line: 'C', gen: 4, year: 1880, t: 2274.68, kind: 'person',
      name: 'Joseph Bitournay Jr. (weaver)',
      sub: 'b. 1880 Redford NY · weaver · m. Maria Lepage 1908',
      parents: ['C-BITSR'] },

    /* 1908 marriage at North Adams: Joseph Bitournay Jr × Maria Lepage */
    { id: 'UN-BIT-LEPAGE', line: 'C', gen: 0, year: 1908, t: 2289.54, kind: 'union',
      name: 'Joseph Bitournay ⚭ Maria Lepage',
      sub: '25 Aug 1908 · Notre Dame du Sacré Coeur, North Adams · Rita\'s parents',
      parents: ['C-BITJR', 'E7-MARIA'] },

    /* ---- Narrated Part 1B spouses (small side-nodes) ---- */
    { id: 'SP-NOYON', line: 'A', gen: 10, year: 1671, t: 911.41, kind: 'spouse',
      name: 'Marie Françoise de Noyon',
      sub: 'm. A10 Jean Barbeau · 1686 Boucherville',
      parents: [], spouseOf: 'A10' },
    { id: 'SP-LAVOIE-PICARD', line: 'D', gen: 99, year: 1656, t: 713.15, kind: 'spouse',
      name: 'Pierre de la Voye dit Le Picard',
      sub: 'Picardy · crossed 1656 · Lavoie founder',
      parents: [], standalone: true },
    { id: 'SP-AGNES', line: 'D', gen: 7, year: 1769, t: 1260.5, kind: 'spouse',
      name: 'Agnès Lavoie',
      sub: 'm. D7 · 1790 Rimouski · 1st wife',
      parents: ['SP-LAVOIE-PICARD'], spouseOf: 'D7' },
    /* Victoire Bouillon — John Jacob's 2nd wife (1798).
       Per narration: the direct Heppell line ran through Victoire, not Agnès. */
    { id: 'SP-D7-VICTOIRE', line: 'D', gen: 7, year: 1775, t: 1289.72, kind: 'spouse',
      name: 'Victoire Bouillon',
      sub: 'm. D7 · 1798 Rimouski · 2nd wife · the line passed through her',
      spouseOf: 'D7', secondSpouse: true },
    { id: 'SP-BLAIS', line: 'A', gen: 5, year: 1840, t: 1400.92, kind: 'spouse',
      name: 'Marie Blais',
      sub: 'm. A5 · 1865 Napierville',
      parents: [], spouseOf: 'A5' },
    { id: 'SP-BOULERICE', line: 'B', gen: 5, year: 1859, t: 1959, kind: 'spouse',
      name: 'Élise Boulerisse',
      sub: 'm. B5 · 1878 Napierville',
      parents: [], spouseOf: 'B5' },
    { id: 'SP-FORGUES', line: 'A', gen: 6, year: 1810, t: 1553.24, kind: 'spouse',
      name: 'Catherine Forgues',
      sub: 'm. A6 · 1828 St-Constant',
      parents: [], spouseOf: 'A6' },

    /* ---- Unions (the trunk, 4 → 2 → 1) ---- */
    { id: 'UN-AB', line: 'TRUNK', gen: 0, year: 1931, t: 2676.42, kind: 'union',
      name: 'Regina ⚭ Ernest',
      sub: '7 Sep 1931 · Williamstown, MA',
      parents: ['B3', 'A3'] },
    { id: 'UN-CD', line: 'TRUNK', gen: 0, year: 1935, t: 2810.76, kind: 'union',
      name: 'Rita ⚭ Alcide',
      sub: '1935 · Fall River, MA',
      parents: ['C3', 'D3'] },
    { id: 'UN-FINAL', line: 'TRUNK', gen: 0, year: 1964, t: 2614.42, kind: 'union',
      name: 'Ronald ⚭ Lorraine',
      sub: '28 Nov 1964 · Notre Dame Church, North Adams · four lines become one',
      parents: ['D2', 'A2'], finalUnion: true },

    /* ---- GEN1: dimmed at opening (t=60), lit at the end (tLight=850/855) ---- */
    { id: 'GEN1-D', line: 'TRUNK', gen: 1, year: 1965, t: 2637.36, tLight: 2572.33,
      kind: 'descendant',
      name: 'Daniel Lepel',
      sub: 'b. 1965 · North Adams, MA',
      parents: ['UN-FINAL'], dimmedUntilLight: true },
    { id: 'GEN1-R', line: 'TRUNK', gen: 1, year: 1968, t: 2637.36, tLight: 2582.01,
      kind: 'descendant',
      name: 'Renée Lepel Hanson',
      sub: 'b. 1968 · North Adams, MA',
      parents: ['UN-FINAL'], dimmedUntilLight: true },

    /* ---- Ronald's brothers (Alcide & Rita's other sons) + Paul's family ---- */
    { id: 'D2-PAUL', line: 'D', gen: 2, year: 1941, t: 2810.96, kind: 'person',
      name: 'Paul A. Lepel',
      sub: 'U.S. Air Force · Elmendorf AFB, Alaska · computer programmer 23 yrs',
      parents: ['UN-CD'] },
    { id: 'D2-ROGER', line: 'D', gen: 2, year: 1945, t: 2978.68, kind: 'person',
      name: 'Roger Lepel',
      sub: 'Ronald\'s brother',
      parents: ['UN-CD'] },
    { id: 'SP-D2-PAUL', line: 'D', gen: 2, year: 1945, t: 2906.8, kind: 'spouse',
      name: 'Judy Darling',
      sub: 'm. Paul Lepel · retired in Florida',
      spouseOf: 'D2-PAUL' },
    { id: 'UN-PAUL-JUDY', line: 'D', gen: 0, year: 1968, t: 2978.68, kind: 'union',
      name: 'Paul ⚭ Judy',
      sub: 'Lepel · Darling',
      parents: ['D2-PAUL', 'SP-D2-PAUL'] },
    { id: 'GEN1-JP', line: 'TRUNK', gen: 1, year: 1969, t: 2691.18, tLight: 2766.26,
      kind: 'descendant',
      name: 'Jon Paul Lepel',
      sub: 'b. Jan 1969 · Daniel\'s cousin',
      parents: ['UN-PAUL-JUDY'], dimmedUntilLight: true },
    { id: 'GEN1-CH', line: 'TRUNK', gen: 1, year: 1974, t: 2843.3, tLight: 2770.66,
      kind: 'descendant',
      name: 'Christine Lepel',
      sub: 'b. Dec 1974 · Daniel\'s cousin',
      parents: ['UN-PAUL-JUDY'], dimmedUntilLight: true }
  ];

  /* =====================================================================
     WORLDS — dated annotations along the time ruler (canonical Part 2)
     Once revealed, they stay. The finished frame shows them all.
     ===================================================================== */
  var WORLDS = [
    /* === France: religious upheaval before the family crossings === */
    { id: 'W1562',         year: 1580, t: 135.18,
      label: 'French Wars of Religion · 1562-1598', pairWith: null,
      band: { from: 1562, to: 1598 } },
    { id: 'W1598',         year: 1598, t: 129.06,
      label: 'Edict of Nantes signed · Henri IV grants religious peace',
      pairWith: null },
    { id: 'W1608',         year: 1608, t: 220.78,
      label: 'Quebec City founded by Champlain', pairWith: null },
    { id: 'W1610',         year: 1610, t: 229.06,
      label: 'Henri IV assassinated · Louis XIII reign begins',
      pairWith: null },

    /* === Thirty Years' War: devastates the Rhineland (Heppell ancestral home) === */
    { id: 'W1618',         year: 1633, t: 397.86,
      label: 'Thirty Years\' War · 1618-1648 · devastates the Rhineland',
      pairWith: 'D9', band: { from: 1618, to: 1648 } },
    { id: 'W1642',         year: 1642, t: 639.76,
      label: 'Montreal founded', pairWith: null },
    { id: 'W1648',         year: 1648, t: 424.68,
      label: 'Peace of Westphalia ends the Thirty Years\' War',
      pairWith: null },
    { id: 'W1661',         year: 1661, t: 619,
      label: 'Louis XIV begins personal reign', pairWith: null },

    /* === The crossings: Carignan-Salières and the troupes de la marine === */
    { id: 'W1665',         year: 1665, t: 656.72,
      label: 'Carignan-Salières arrives · 1,200 soldiers',
      pairWith: 'C12' },
    { id: 'W1666',         year: 1666, t: 698,
      label: 'Mohawk campaigns', pairWith: null },
    { id: 'W1668',         year: 1668, t: 702.44,
      label: 'Regiment disbanded · ~400 stay', pairWith: null },
    { id: 'W1672', quiet: true,         year: 1675, t: 760.86,
      label: 'Franco-Dutch War · 1672-1678', pairWith: null,
      band: { from: 1672, to: 1678 } },
    { id: 'W1685-edit',    year: 1685, t: 844.31,
      label: 'Revocation of the Edict of Nantes · Protestantism outlawed',
      pairWith: 'A10' },
    { id: 'W1685-denon',   year: 1685, t: 834.21,
      label: 'Denonville · troupes de la marine', pairWith: 'A10' },

    /* === Late 17th to mid-18th century: Quebec consolidates, France wars === */
    { id: 'W1701',         year: 1701, t: 969.78,
      label: 'Great Peace of Montreal with First Nations',
      pairWith: null },
    { id: 'W1701s',        year: 1707, t: 987.72,
      label: 'War of Spanish Succession · Queen Anne\'s War · 1701-1714',
      pairWith: null, band: { from: 1701, to: 1714 } },
    { id: 'W1709',         year: 1709, t: 1000.76,
      label: 'Le Grand Hiver · the Great Famine devastates France',
      pairWith: null },
    { id: 'W1713',         year: 1713, t: 1014.98,
      label: 'Treaty of Utrecht · Britain gains Acadia and Newfoundland',
      pairWith: null },
    { id: 'W1740',         year: 1744, t: 1051.36,
      label: 'War of Austrian Succession · King George\'s War · 1740-1748',
      pairWith: null, band: { from: 1740, to: 1748 } },

    /* === The Conquest: French and Indian War, fall of New France === */
    { id: 'W1755',         year: 1755, t: 1125.5,
      label: 'Acadian Expulsion · Le Grand Dérangement',
      pairWith: null },
    { id: 'W1756',         year: 1759, t: 1149.58,
      label: 'Seven Years\' War · French and Indian War · 1756-1763',
      pairWith: null, band: { from: 1756, to: 1763 } },
    { id: 'W1759',         year: 1759, t: 1160.02,
      label: 'Battle of the Plains of Abraham · Quebec falls',
      pairWith: null },
    { id: 'W1763',         year: 1763, t: 1176.16,
      label: 'Treaty of Paris · New France ceded to Britain',
      pairWith: 'A7' },
    { id: 'W1774',         year: 1774, t: 1219.8,
      label: 'Quebec Act preserves French civil law and Catholic religion',
      pairWith: null },

    /* === Revolutions and the long 19th century === */
    { id: 'W1775',         year: 1779, t: 1238.66,
      label: 'American Revolution · 1775-1783', pairWith: null,
      band: { from: 1775, to: 1783 } },
    { id: 'W1789',         year: 1794, t: 1478.64,
      label: 'French Revolution · 1789-1799', pairWith: null,
      band: { from: 1789, to: 1799 } },
    { id: 'W1803',         year: 1809, t: 1487.32,
      label: 'Napoleonic Wars · 1803-1815', pairWith: null,
      band: { from: 1803, to: 1815 } },
    { id: 'W1837',         year: 1838, t: 1584.3,
      label: 'Lower Canada Rebellion · 1837-1838', pairWith: null },
    { id: 'W1840-1930',    year: 1885, t: 2037.16,
      label: 'French-Canadian mill migration · 1840-1930 · ~900,000',
      pairWith: null, band: { from: 1840, to: 1930 } },

    /* === Confederation, the Franco-Prussian War, the modern era === */
    { id: 'W1867',         year: 1867, t: 1919.6,
      label: 'Canadian Confederation', pairWith: null },
    { id: 'W1870',         year: 1871, t: 2013.72,
      label: 'Franco-Prussian War · German Empire founded · 1870-1871',
      pairWith: null, band: { from: 1870, to: 1871 } },
    { id: 'W1914',         year: 1916, t: 2342.02,
      label: 'World War I · 1914-1918', pairWith: null,
      band: { from: 1914, to: 1918 } },
    { id: 'W1929',         year: 1932, t: 2371.32,
      label: 'Great Depression · 1929-1939', pairWith: null,
      band: { from: 1929, to: 1939 } },
    { id: 'W1939',         year: 1942, t: 2434.38,
      label: 'World War II · 1939-1945', pairWith: null,
      band: { from: 1939, to: 1945 } },
    { id: 'W1950',         year: 1952, t: 2478.16,
      label: 'Korean War · 1950-1953', pairWith: null,
      band: { from: 1950, to: 1953 } },
    { id: 'W2025',         year: 2025, t: 2704.2,
      label: 'Bill C-3 takes effect · 15 December 2025',
      pairWith: 'A4' }
  ];

  /* =====================================================================
     MIGRATIONS — map ARROWs. Each opens a map-inset surface window of
     [t, t + tHold]. The inset slides in, holds, slides out.
     ===================================================================== */
  var MIGRATIONS = [
    /* === Crossings (arrows) — each fires AT the beat that narrates it === */
    { id: 'M-adrien',   t: 675.68,  tHold: 22,
      label: '1665 · Adrien Bétourné · Picardy → Quebec',
      line: 'C', from: [49.42, 1.94],  to: [46.81, -71.21] },
    { id: 'L-laprairie', t: 730.84, tHold: 26, line: 'C', isLocation: true,
      label: "Adrien's grant \u00b7 south shore \u00b7 Longueuil & La Prairie",
      from: [45.45, -73.50], to: null },
    { id: 'M-twoparts', t: 1652.4, tHold: 7, line: 'TRUNK',
      label: 'By 1850 \u00b7 two parts of Quebec \u00b7 Napierville & L\u00e9vis',
      points: [ { pt: [45.18, -73.40], line: 'A' }, { pt: [46.78, -71.18], line: 'E' } ] },
    { id: 'L-napierville', t: 1659.34, tHold: 5, line: 'A', isLocation: true, zoom: 9,
      label: 'Saint-\u00c9douard de Napierville \u00b7 Mont\u00e9r\u00e9gie',
      from: [45.18, -73.40], to: null },
    { id: 'L-levis', t: 1665.04, tHold: 11, line: 'E', isLocation: true, zoom: 9,
      label: 'L\u00e9vis \u00b7 south shore of the Saint Lawrence',
      from: [46.78, -71.18], to: null },
    { id: 'L-bellechasse', t: 1676.84, tHold: 14, line: 'E', isLocation: true, zoom: 9,
      label: 'Seigneurie of Bellechasse \u00b7 south shore',
      from: [46.62, -70.90], to: null },
    { id: 'M-twoparts2', t: 1990.5, tHold: 11, line: 'TRUNK',
      label: 'L\u00e9vis & Napierville \u00b7 the two parts of Quebec',
      points: [ { pt: [46.78, -71.18], line: 'E' }, { pt: [45.18, -73.40], line: 'A' } ] },
    { id: 'M-jean',     t: 875.43,  tHold: 28,
      label: '1685 · Jean Barbeau · Pons → Quebec',
      line: 'A', from: [45.58, -0.55], to: [45.59, -73.45] },
    { id: 'M-mongeau',  t: 1031.15,  tHold: 22,
      label: 'After 1736 · Mongeau · Auvergne → Quebec',
      line: 'B', from: [45.78, 3.08],  to: [45.59, -73.45],
      candidate: true },
    { id: 'M-heppell',  t: 1069.74,  tHold: 22,
      label: 'Heppell · Rhineland → New Jersey',
      line: 'D', from: [49.61, 7.34],  to: [39.57, -75.46] },
    { id: 'M-johnjacob', t: 1252.04, tHold: 22,
      label: '1790 · John Jacob Heppell · New Jersey → Rimouski',
      line: 'D', from: [39.57, -75.46], to: [48.45, -68.52] },
    { id: 'M-modeste',  t: 2065.96,  tHold: 22,
      label: 'French-Canadian mill migration · Quebec → New England',
      line: 'C', from: [45.32, -73.41], to: [42.70, -73.11] },
    { id: 'M-henri',    t: 2079.98,  tHold: 22,
      label: '1897 · Henri Clermont · Quebec → Berkshires',
      line: 'B', from: [45.65, -72.78], to: [42.72, -73.20] },
    { id: 'M-hermenegilde', t: 2107.22, tHold: 22,
      label: '1900 · Hermenegilde Hepel · Quebec → Fall River',
      line: 'D', from: [48.78, -67.72], to: [41.70, -71.16] },
    { id: 'M-daniel',   t: 2924.26,  tHold: 16,
      label: 'Daniel · North Adams → Albany, NY',
      line: 'TRUNK', from: [42.70, -73.11], to: [42.65, -73.76] },
    { id: 'M-converge', t: 575.3, tHold: 26, line: 'TRUNK',
      label: 'Four families · Picardy · Auvergne · Rhineland · Saintonge \u2192 the Berkshires',
      converge: [ { pt: [49.42, 1.94], line: 'C' }, { pt: [45.78, 3.08], line: 'B' },
                  { pt: [49.61, 7.34], line: 'D' }, { pt: [45.58, -0.55], line: 'A' } ],
      to: [42.70, -73.11] },

    /* === Single-point location pins (no arrow) — fire WHEN each region is
       first named in the narration, not before. */
    { id: 'L-stlawrence', t: 174.52, tHold: 18, line: 'TRUNK', isLocation: true,
      label: 'Saint Lawrence · Champlain\'s maps · 1603',
      from: [46.81, -71.21], to: null },
    { id: 'L-picardy', zoom: 7,     t: 171.74, tHold: 48, line: 'C', isLocation: true,
      label: 'Picardy · Saint-Crépin-Ibouvilliers',
      from: [49.42, 1.94], to: null },
    { id: 'L-quebec',      t: 220.38, tHold: 14, line: 'TRUNK', isLocation: true,
      label: 'Quebec City founded · 1608',
      from: [46.81, -71.21], to: null },
    { id: 'L-rouen', zoom: 7,       t: 273.69, tHold: 14, line: 'C', isLocation: true,
      label: 'Rouen · Charles Bétourné died here · 1660',
      from: [49.44, 1.10], to: null },
    { id: 'L-auvergne', zoom: 7,    t: 310.42, tHold: 22, line: 'B', isLocation: true,
      label: 'Auvergne · Clermont-Ferrand',
      from: [45.78, 3.08], to: null },
    { id: 'L-rhineland', zoom: 7,   t: 438.02, tHold: 76, line: 'D', isLocation: true,
      label: 'Rhineland · Baumholder',
      from: [49.61, 7.34], to: null },
    { id: 'L-saintonge', zoom: 7,   t: 484.12, tHold: 50, line: 'A', isLocation: true,
      label: 'Saintonge · Pons',
      from: [45.58, -0.55], to: null }
  ];

  /* =====================================================================
     BEATS — the 40-beat cue sheet. Used for caption display and as the
     camera-walk anchor list. Re-lock .t to the final audio later.
     ===================================================================== */
  var BEATS = [
    { t: 0.00, narration: "Every living person is the survivor of an unbroken line.", focus: null },
    { t: 35.64, narration: "Now and then, a few of those branches can still be followed.", focus: null },
    { t: 59.50, narration: "Four lines of descent, across four countries and more than four centuries.", focus: "RULER" },
    { t: 76.24, narration: "It begins in 1604, in a village in the north of France.", focus: "RULER" },
    { t: 93.50, narration: "And then, four separate families become one.", focus: "OVERVIEW" },
    { t: 171.64, narration: "Jehan Bétourné carried his newborn son to the parish church to be baptised.", focus: "C14" },
    { t: 188.94, narration: "The child was named Charles Bétourné.", focus: "C13" },
    { t: 273.59, narration: "Married Marguerite. Died at Rouen in 1660.", focus: "SP-C13" },
    { t: 285.68, narration: "Their son Adrien, born 1635, lost both parents young.", focus: "C12" },
    { t: 310.32, narration: "In Clermont-Ferrand, a Catholic family named Mangot worshipped at Saint-Pierre.", focus: "B12" },
    { t: 328.32, narration: "The deepest of them is Mathieu Mangot.", focus: "B12" },
    { t: 341.22, narration: "They were carpenters. The family stayed for four documented generations.", focus: "B11" },
    { t: 373.10, narration: "Gabriel Mangault baptised 23 March 1736, at five o’clock in the morning.", focus: "B9" },
    { t: 437.92, narration: "In the Rhineland, the Heppells lived as German Lutherans near Baumholder.", focus: "D9" },
    { t: 446.10, narration: "Philipp Jacob Heppell and Margretha raised their children there.", focus: "D9" },
    { t: 465.78, narration: "Their son Johann Nicolaus Heppell was baptised 22 July 1707.", focus: "D8" },
    { t: 500.96, narration: "In Saintonge, Pierre Barbeau and Madeleine Babin were raising a family.", focus: "A11" },
    { t: 522.24, narration: "In 1666 they had a son named Jean.", focus: "A10" },
    { t: 575.20, narration: "These four European families would all eventually send descendants to one mill town.", focus: null },
    { t: 656.62, narration: "The Carignan-Salières Regiment disembarked at Quebec City.", focus: "W1665" },
    { t: 675.58, narration: "Among the soldiers was Adrien Bétourné.", focus: "C12" },
    { t: 749.89, narration: "Campaigns against the Mohawk. Disbanded 1668. Married Marie Deshaies 1669.", focus: "C12" },
    { t: 822.89, narration: "Twenty years later, a second soldier crossed.", focus: "RULER" },
    { t: 834.11, narration: "Troupes de la marine sailed with the marquis de Denonville.", focus: "W1685-denon" },
    { t: 844.21, narration: "Louis XIV revoked the Edict of Nantes.", focus: "W1685-edit" },
    { t: 875.33, narration: "He was Jean Barbeau, the merchant’s son. Nickname: Boisdoré.", focus: "A10" },
    { t: 911.41, narration: "Married Marie Françoise de Noyon, 18 November 1686, Boucherville.", focus: "A10" },
    { t: 957.08, narration: "Through their son Gabriel, baptised 1694; Gabriel’s son Jean-Baptiste, 1725.", focus: "A9" },
    { t: 1006.27, narration: "Pierre de la Voye dit Le Picard had crossed in 1656.", focus: "SP-LAVOIE-PICARD" },
    { t: 1027.34, narration: "In Auvergne, the Mangot carpenters became Mongeau dit Clermont.", focus: "B8" },
    { t: 1085.70, narration: "The Heppells crossed. John Jacob Jean Heppell born 1750, New Jersey.", focus: "D7" },
    { t: 1105.74, narration: "Joseph Barbeau dit Boisdoré baptised at Saint-Constant in 1757.", focus: "A7" },
    { t: 1176.06, narration: "Six years old when the Treaty of Paris handed New France to Britain.", focus: "W1763" },
    { t: 1238.56, narration: "In 1775 the American Revolution broke out.", focus: "W1775" },
    { t: 1260.50, narration: "John Jacob Heppell married Agnès Lavoie 1790, Rimouski.", focus: "SP-AGNES" },
    { t: 1311.76, narration: "The surname slid from Heppell to Epelle to Hepel.", focus: "D7" },
    { t: 1319.50, narration: "In Lauzon, on the south shore of the Saint Lawrence, the Lepage line begins.", focus: "E11" },
    { t: 1353.58, narration: "Michel Lepage married Catherine Huard at Lauzon, 1805.", focus: "E10" },
    { t: 1400.92, narration: "Joseph Lepage the pit sawyer married Josephte Couture, 1846.", focus: "E9" },
    { t: 1543.24, narration: "François Régis Barbeau born at Saint-Constant in 1804. M. Catherine Forgues 1828.", focus: "A6" },
    { t: 1608.60, narration: "By the early 1800s the old nicknames were fading.", focus: "A7" },
    { t: 1676.74, narration: "In Saint-Michel de Bellechasse, Laurent Noel and Marguerite Duquet.", focus: "F-NOEL" },
    { t: 1706.52, narration: "Virginie Noel, baptised 1855, orphan at fifteen.", focus: "F-VIRGINIE" },
    { t: 1751.54, narration: "Joseph Lepage Jr. married Virginie Noel, 1873, at Notre-Dame-de-la-Victoire.", focus: "UN-LEPAGE-NOEL" },
    { t: 1814.06, narration: "Joseph Lepage Jr., charpentier — their son.", focus: "E8" },
    { t: 1873.26, narration: "At Saint-Édouard de Napierville, three lines were converging.", focus: "C5" },
    { t: 1884.70, narration: "Magloire Barbeau married Marie Blais, 1865.", focus: "A5" },
    { t: 2039.94, narration: "The mills called. Roughly 900,000 French-Canadians left Quebec.", focus: "W1840-1930" },
    { t: 2192.16, narration: "Marie Helene Cleophee Lepage, b. 1883 — Daniel's paternal great-grandmother.", focus: "E7-MARIA" },
    { t: 2214.20, narration: "All four lines were converging on the Berkshire Hills.", focus: null },
    { t: 2371.22, narration: "Ernest Barbeau and Regina Clermont married 1931.", focus: "UN-AB" },
    { t: 2409.82, narration: "Rita Betourney born 1914. Alcide Lepel born 1911. They married.", focus: "UN-CD" },
    { t: 2691.18, narration: "Jon Lepel lives in the same state.", focus: "GEN1-JP" },
    { t: 2704.10, narration: "Bill C-3 took effect, 15 December 2025.", focus: "W2025" },
    { t: 2730.76, narration: "The research reached back four hundred and twenty-two years.", focus: "OVERVIEW" },
    { t: 2746.19, narration: "This is who they came from. This is how they got here.", focus: "OVERVIEW" },
    { t: 2759.42, narration: "Traced the Barbeau line back to a merchant house in Pons.", focus: "A11", highlight: "A" },
    { t: 2775.70, narration: "Joseph Wilfred Barbeau baptised 1870. The documentary anchor for Bill C-3.", focus: "A4" },
    { t: 2906.80, narration: "Ronald had two brothers: Paul and Roger.", focus: "DESCENDANTS" },
    { t: 2919.07, narration: "Aunt Judy is still living, retired in Florida.", focus: "DESCENDANTS" },
    { t: 2924.26, narration: "Daniel and Renee grew up in North Adams. Daniel moved to Albany.", focus: "GEN1-D" },
    { t: 2992.44, narration: "Ronald Joseph Lepel married Lorraine Irene Barbeau. The four lines became one.", focus: "UN-FINAL" },
  ];

  /* CONFIG: surfaces the time-axis range so the engine and ruler share
     identical year-to-x math. */
  var TIME = { yearMin: 1600, yearMax: 2030 };

  window.LINEAGE_DATA = {
    LINES: LINES,
    PEOPLE: PEOPLE,
    WORLDS: WORLDS,
    MIGRATIONS: MIGRATIONS,
    BEATS: BEATS,
    TIME: TIME
  };
})();
